// GENERATED by scripts/build-tokens.mjs — do not edit by hand.
// Source of truth: the DTCG token files (*.tokens.json) + themes.ts.
// Keys mirror the --sv-* CSS custom properties (without the prefix).

export type Palette = Record<string, string>;

export type TokenName =
  | 'bg'
  | 'surface-1'
  | 'surface-2'
  | 'surface-3'
  | 'border'
  | 'text'
  | 'text-strong'
  | 'text-muted'
  | 'text-faint'
  | 'accent'
  | 'accent-2'
  | 'accent-rust'
  | 'mix-target'
  | 'success'
  | 'error'
  | 'warning'
  | 'syn-keyword'
  | 'syn-string'
  | 'syn-var'
  | 'syn-func'
  | 'syn-comment'
  | 'syn-number';

export type ThemeName = 'dark' | 'light';

const darkTokens: Record<TokenName, string> = {
  bg: '#191919',
  'surface-1': '#1e1e1e',
  'surface-2': '#252526',
  'surface-3': '#2d2d2d',
  border: '#3c3c3c',
  text: '#d4d4d4',
  'text-strong': '#f5f5f5',
  'text-muted': '#9a9a9a',
  'text-faint': '#858585',
  accent: '#4ec9b0',
  'accent-2': '#e06c75',
  'accent-rust': '#ce9178',
  'mix-target': '#ffffff', // hover lightens in dark
  success: '#74a55e',
  error: '#ff5b48',
  warning: '#ffa500',
  'syn-keyword': '#569cd6',
  'syn-string': '#ce9178',
  'syn-var': '#9cdcfe',
  'syn-func': '#dcdcaa',
  'syn-comment': '#74a55e',
  'syn-number': '#b5cea8'
};

export const dark: Palette = darkTokens;

const lightTokens: Record<TokenName, string> = {
  bg: '#f1e7c4',
  'surface-1': '#ece1b8',
  'surface-2': '#e6dcb2',
  'surface-3': '#e0d5a8',
  border: '#c7ba85',
  text: '#3a3527',
  'text-strong': '#2a2617',
  'text-muted': '#605b47',
  'text-faint': '#65604b',
  accent: '#1f6659',
  'accent-2': '#8d3740',
  'accent-rust': '#874a30',
  'mix-target': '#000000', // hover darkens in light
  success: '#086326',
  error: '#9d2b20',
  warning: '#7d4800',
  'syn-keyword': '#274a86',
  'syn-string': '#8a4326',
  'syn-var': '#2f3f6e',
  'syn-func': '#6a531f',
  'syn-comment': '#525f36',
  'syn-number': '#2f5f45'
};

export const light: Palette = lightTokens;

export const palettes: Record<ThemeName, Readonly<Record<TokenName, string>>> = {
  dark: darkTokens,
  light: lightTokens
};
