// QSS emitter — a complete Qt Style Sheet per theme for BONES's PySide6
// desktop app (whole-app swap via QApplication.setStyleSheet). QSS has no
// variables, so every value is inlined from the resolved token map; hover/
// pressed states come precomputed through the same oklab math the web hover
// convention uses (see prepare.mjs HOVER_MIX/PRESSED_MIX).
//
// Conventions that deliberately differ from the web components:
//   - base font-size 14px (fs-sm): desktop density, vs 16px web body
//   - :pressed at 25% mix: the web defines no pressed state
// Both are single constants — adjust in prepare.mjs / BASE_FONT_KEY below.

const BASE_FONT_KEY = 'fs-sm';

const px = (value) => {
  const n = Number.parseFloat(value);
  if (Number.isNaN(n)) throw new Error(`emitQss: expected a px length, got "${value}"`);
  return n;
};

export const emitQss = (theme) => {
  const scaleQt = new Map(theme.scaleFull.map((row) => [row.key, row.qt]));
  const derived = new Map(theme.derived.map((d) => [d.key, d.css]));
  const c = (key) => {
    const value = theme.paletteHex[key];
    if (value === undefined) throw new Error(`emitQss: missing color token "${key}"`);
    return value;
  };
  const dv = (key) => {
    const value = derived.get(key);
    if (value === undefined) throw new Error(`emitQss: missing derived token "${key}"`);
    return value;
  };
  const s = (key) => {
    const value = scaleQt.get(key);
    if (value === undefined) throw new Error(`emitQss: missing scale token "${key}"`);
    return value;
  };

  const padV = px(s('space-2')); // 8
  const padH = px(s('space-4')); // 16
  const padInputH = px(s('space-3')); // 12

  return `/* GENERATED by scripts/build-tokens.mjs — do not edit by hand.
 * Theme: ${theme.name} — Qt Style Sheet for @svnbjrn/design.
 *
 * Apply whole-app:  app.setStyleSheet(Path(".../qss/${theme.name}.qss").read_text())
 *
 * Variant selectors use dynamic properties, e.g.
 *   button.setProperty("class", "primary")
 * Qt does NOT restyle on property changes — re-polish after setProperty:
 *   button.style().unpolish(button); button.style().polish(button); button.update()
 */

* {
  font-family: ${s('font-sans')};
  font-size: ${s(BASE_FONT_KEY)};
  color: ${c('text')};
}

QMainWindow, QDialog {
  background: ${c('bg')};
}

QWidget#svSurface {
  background: ${c('surface-1')};
}

/* ── Buttons ─────────────────────────────────────────────────────────── */

QPushButton {
  background: ${c('surface-2')};
  color: ${c('text')};
  border: 1px solid ${c('border')};
  border-radius: ${s('radius-md')};
  padding: ${padV}px ${padH}px;
  font-weight: ${s('font-weight-medium')};
}
QPushButton:hover {
  background: ${dv('surface-2-hover')};
}
QPushButton:pressed {
  background: ${dv('surface-2-pressed')};
}
QPushButton:focus {
  border: 2px solid ${c('accent')};
  padding: ${padV - 1}px ${padH - 1}px;
}
QPushButton:disabled {
  background: ${c('surface-1')};
  color: ${c('text-faint')};
  border-color: ${c('border')};
}

QPushButton[class="primary"] {
  background: ${c('accent')};
  color: ${c('bg')};
  border: none;
  padding: ${padV + 1}px ${padH + 1}px;
}
QPushButton[class="primary"]:hover {
  background: ${dv('accent-hover')};
}
QPushButton[class="primary"]:pressed {
  background: ${dv('accent-pressed')};
}
QPushButton[class="primary"]:focus {
  border: 2px solid ${c('text-strong')};
  padding: ${padV - 1}px ${padH - 1}px;
}
QPushButton[class="primary"]:disabled {
  background: ${c('surface-3')};
  color: ${c('text-faint')};
}

QPushButton[class="danger"] {
  background: ${c('error')};
  color: #ffffff;
  border: none;
  padding: ${padV + 1}px ${padH + 1}px;
}
QPushButton[class="danger"]:hover {
  background: ${dv('error-hover')};
}
QPushButton[class="danger"]:pressed {
  background: ${dv('error-pressed')};
}
QPushButton[class="danger"]:focus {
  border: 2px solid ${c('text-strong')};
  padding: ${padV - 1}px ${padH - 1}px;
}
QPushButton[class="danger"]:disabled {
  background: ${c('surface-3')};
  color: ${c('text-faint')};
}

QPushButton[class="ghost"] {
  background: transparent;
  color: ${c('text-muted')};
  border: none;
  padding: ${padV + 1}px ${padH + 1}px;
}
QPushButton[class="ghost"]:hover {
  background: ${c('surface-2')};
  color: ${c('text')};
}
QPushButton[class="ghost"]:pressed {
  background: ${dv('surface-2-pressed')};
}
QPushButton[class="ghost"]:disabled {
  color: ${c('text-faint')};
}

/* ── Text inputs ─────────────────────────────────────────────────────── */

QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QComboBox {
  background: ${c('surface-2')};
  color: ${c('text')};
  border: 1px solid ${c('border')};
  border-radius: ${s('radius-sm')};
  padding: ${padV}px ${padInputH}px;
  selection-background-color: ${c('accent')};
  selection-color: ${c('bg')};
}
QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QComboBox:focus {
  border: 2px solid ${c('accent')};
  padding: ${padV - 1}px ${padInputH - 1}px;
}
QLineEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled, QSpinBox:disabled, QDoubleSpinBox:disabled, QComboBox:disabled {
  background: ${c('surface-1')};
  color: ${c('text-faint')};
}
QLineEdit[hasError="true"] {
  border: 2px solid ${c('error')};
  padding: ${padV - 1}px ${padInputH - 1}px;
}

QComboBox::drop-down {
  border: none;
  width: ${padH + 8}px;
}
QComboBox QAbstractItemView {
  background: ${c('surface-2')};
  border: 1px solid ${c('border')};
  border-radius: ${s('radius-md')};
  selection-background-color: ${c('surface-3')};
  selection-color: ${c('accent')};
  outline: 0;
}

/* ── Menus ───────────────────────────────────────────────────────────── */

QMenuBar {
  background: ${c('surface-1')};
  border-bottom: 1px solid ${c('border')};
}
QMenuBar::item {
  padding: ${padV - 2}px ${padInputH}px;
  background: transparent;
}
QMenuBar::item:selected {
  background: ${c('surface-3')};
  border-radius: ${s('radius-sm')};
}

QMenu {
  background: ${c('surface-2')};
  border: 1px solid ${c('border')};
  border-radius: ${s('radius-lg')};
  padding: ${padV - 4}px;
}
QMenu::item {
  padding: ${padV}px ${padInputH}px;
  border-radius: ${s('radius-sm')};
  min-height: 28px;
}
QMenu::item:selected {
  background: ${c('surface-3')};
}
QMenu::item:disabled {
  color: ${c('text-faint')};
}
QMenu::separator {
  height: 1px;
  background: ${c('border')};
  margin: ${padV - 4}px ${padV}px;
}

QToolTip {
  background: ${c('surface-3')};
  color: ${c('text-strong')};
  border: 1px solid ${c('border')};
  border-radius: ${s('radius-sm')};
  padding: ${padV - 4}px ${padV}px;
  font-size: ${s('fs-xs')};
}

/* ── Scrollbars ──────────────────────────────────────────────────────── */

QScrollBar:vertical {
  background: transparent;
  width: 8px;
  margin: 0;
}
QScrollBar:horizontal {
  background: transparent;
  height: 8px;
  margin: 0;
}
QScrollBar::handle:vertical, QScrollBar::handle:horizontal {
  background: ${c('border')};
  border-radius: 4px;
  min-height: 24px;
  min-width: 24px;
}
QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {
  background: ${c('text-faint')};
}
QScrollBar::add-line, QScrollBar::sub-line {
  height: 0;
  width: 0;
}
QScrollBar::add-page, QScrollBar::sub-page {
  background: transparent;
}

/* ── Tabs ────────────────────────────────────────────────────────────── */

QTabWidget::pane {
  border: 1px solid ${c('border')};
  background: ${c('surface-1')};
  border-radius: ${s('radius-md')};
}
QTabBar::tab {
  background: transparent;
  color: ${c('text-muted')};
  padding: ${padV}px ${padInputH}px;
  border-bottom: 2px solid transparent;
}
QTabBar::tab:selected {
  color: ${c('accent')};
  border-bottom: 2px solid ${c('accent')};
}
QTabBar::tab:hover:!selected {
  color: ${c('text')};
}

/* ── Checkables ──────────────────────────────────────────────────────── */

QCheckBox, QRadioButton {
  spacing: ${padV}px;
  color: ${c('text')};
}
QCheckBox::indicator, QRadioButton::indicator {
  width: 16px;
  height: 16px;
  border: 1px solid ${c('border')};
  background: ${c('surface-2')};
}
QCheckBox::indicator {
  border-radius: ${s('radius-sm')};
}
QRadioButton::indicator {
  border-radius: 8px;
}
QCheckBox::indicator:hover, QRadioButton::indicator:hover {
  border-color: ${c('accent')};
}
QCheckBox::indicator:checked, QRadioButton::indicator:checked {
  background: ${c('accent')};
  border-color: ${c('accent')};
}
QCheckBox:disabled, QRadioButton:disabled {
  color: ${c('text-faint')};
}
QCheckBox::indicator:disabled, QRadioButton::indicator:disabled {
  background: ${c('surface-1')};
  border-color: ${c('border')};
}

/* ── Containers & chrome ─────────────────────────────────────────────── */

QGroupBox {
  border: 1px solid ${c('border')};
  border-radius: ${s('radius-lg')};
  margin-top: ${padInputH}px;
  padding: ${padInputH}px;
}
QGroupBox::title {
  subcontrol-origin: margin;
  left: ${padInputH}px;
  padding: 0 ${padV - 4}px;
  color: ${c('text-muted')};
  font-size: ${s('fs-xs')};
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

QStatusBar {
  background: ${c('surface-1')};
  border-top: 1px solid ${c('border')};
  color: ${c('text-muted')};
  font-size: ${s('fs-xs')};
  min-height: 24px;
}
QStatusBar::item {
  border: none;
}

QToolBar {
  background: ${c('surface-1')};
  border-bottom: 1px solid ${c('border')};
  spacing: ${padV - 4}px;
  padding: ${padV - 4}px;
}
QToolButton {
  background: transparent;
  border: none;
  border-radius: ${s('radius-sm')};
  padding: ${padV - 2}px;
  color: ${c('text-muted')};
}
QToolButton:hover {
  background: ${c('surface-2')};
  color: ${c('text')};
}
QToolButton:pressed {
  background: ${dv('surface-2-pressed')};
}
QToolButton:checked {
  background: ${c('surface-3')};
  color: ${c('accent')};
}

QProgressBar {
  background: ${c('surface-3')};
  border: none;
  border-radius: ${s('radius-sm')};
  height: 8px;
  text-align: center;
  color: transparent;
}
QProgressBar::chunk {
  background: ${c('accent')};
  border-radius: ${s('radius-sm')};
}

QSlider::groove:horizontal {
  background: ${c('surface-3')};
  height: 4px;
  border-radius: 2px;
}
QSlider::sub-page:horizontal {
  background: ${c('accent')};
  border-radius: 2px;
}
QSlider::handle:horizontal {
  background: ${c('accent')};
  width: 14px;
  height: 14px;
  margin: -5px 0;
  border-radius: 7px;
}
QSlider::handle:horizontal:hover {
  background: ${dv('accent-hover')};
}

/* ── Item views ──────────────────────────────────────────────────────── */

QListWidget, QListView, QTreeView, QTableView {
  background: ${c('surface-1')};
  border: 1px solid ${c('border')};
  border-radius: ${s('radius-md')};
  alternate-background-color: ${c('surface-2')};
  outline: 0;
}
QListWidget::item, QListView::item, QTreeView::item {
  padding: ${padV - 2}px ${padV}px;
  border-radius: ${s('radius-sm')};
}
QListWidget::item:hover, QListView::item:hover, QTreeView::item:hover {
  background: ${c('surface-2')};
}
QListWidget::item:selected, QListView::item:selected, QTreeView::item:selected {
  background: ${c('surface-3')};
  color: ${c('accent')};
}
QTableView {
  gridline-color: ${c('border')};
  selection-background-color: ${c('surface-3')};
  selection-color: ${c('text-strong')};
}
QHeaderView::section {
  background: ${c('surface-2')};
  color: ${c('text-muted')};
  border: none;
  border-bottom: 1px solid ${c('border')};
  border-right: 1px solid ${c('border')};
  padding: ${padV - 2}px ${padV}px;
  font-size: ${s('fs-xs')};
  font-weight: ${s('font-weight-semibold')};
}

/* ── Status text helpers (setProperty("class", ...) + re-polish) ─────── */

QLabel[class="success"] { color: ${c('success')}; }
QLabel[class="error"] { color: ${c('error')}; }
QLabel[class="warning"] { color: ${c('warning')}; }
QLabel[class="muted"] { color: ${c('text-muted')}; }
QLabel[class="code"] {
  font-family: ${s('font-mono')};
  background: ${c('surface-3')};
  border-radius: ${s('radius-sm')};
  padding: 2px 6px;
}
`;
};
