// CSS emitters: scale.css (@layer sv.base) and colors.css (@layer sv.theme).
// Pure string builders over prepare.mjs rows.

export const GENERATED_HEADER = '/* GENERATED by scripts/build-tokens.mjs — do not edit by hand. */\n';

const cluster = (key) => key.split('-')[0];

const declLines = (rows, indent, { comments = false, clustered = false } = {}) => {
  const lines = [];
  let previousCluster = null;
  for (const row of rows) {
    if (clustered && previousCluster !== null && cluster(row.key) !== previousCluster) {
      lines.push('');
    }
    previousCluster = cluster(row.key);
    if (comments && row.description) {
      lines.push(`${indent}/* ${row.description} */`);
    }
    lines.push(`${indent}--sv-${row.key}: ${row.css};`);
  }
  return lines;
};

/** scale.css — theme-agnostic tokens at :root inside @layer sv.base. */
export const emitScaleCss = (base) =>
  [
    GENERATED_HEADER.trimEnd(),
    '@layer sv.base {',
    '  :root {',
    ...declLines(base.scale, '    ', { comments: true, clustered: true }),
    '  }',
    '}',
    ''
  ].join('\n');

const themeBlock = (selector, theme, indent) => [
  `${indent}${selector} {`,
  ...declLines(theme.colors, `${indent}  `),
  ...declLines(theme.scaleDiff, `${indent}  `),
  `${indent}}`
];

/**
 * colors.css — all built-in themes inside @layer sv.theme:
 *   :root                       default theme
 *   @media (prefers-color-scheme: X) { :root:not([data-theme]) }
 *                               auto-switch themes, beaten by any explicit
 *                               [data-theme] (including future world themes —
 *                               :not([data-theme]) keeps this block's
 *                               specificity out of their way)
 *   [data-theme="name"]         explicit opt-in, one per theme; bare
 *                               attribute selectors so subtree theming
 *                               (<div data-theme="light">) keeps working
 */
export const emitColorsCss = (themes) => {
  const defaultTheme = themes.find((t) => t.isDefault);
  if (!defaultTheme) throw new Error('emitColorsCss: no default theme');
  const lines = [GENERATED_HEADER.trimEnd(), '@layer sv.theme {'];
  lines.push(...themeBlock(':root', defaultTheme, '  '));
  for (const theme of themes) {
    if (theme.isDefault || !theme.prefersColorScheme) continue;
    lines.push(`  @media (prefers-color-scheme: ${theme.prefersColorScheme}) {`);
    lines.push(...themeBlock(':root:not([data-theme])', theme, '    '));
    lines.push('  }');
  }
  for (const theme of themes) {
    lines.push(...themeBlock(`[data-theme="${theme.name}"]`, theme, '  '));
  }
  lines.push('}', '');
  return lines.join('\n');
};
