// DO NOT EDIT: generated by scripts/emitters/emit-tui-rust.mjs
// Source themes: dark, light

use ratatui::style::Color;

pub const DARK: TerminalPalette = TerminalPalette {
    bg: Color::Rgb(25, 25, 25),
    surface_1: Color::Rgb(30, 30, 30),
    surface_2: Color::Rgb(37, 37, 38),
    surface_3: Color::Rgb(45, 45, 45),
    border: Color::Rgb(60, 60, 60),
    text: Color::Rgb(212, 212, 212),
    text_strong: Color::Rgb(245, 245, 245),
    text_muted: Color::Rgb(154, 154, 154),
    text_faint: Color::Rgb(133, 133, 133),
    accent: Color::Rgb(78, 201, 176),
    accent_2: Color::Rgb(224, 108, 117),
    accent_rust: Color::Rgb(206, 145, 120),
    mix_target: Color::Rgb(255, 255, 255),
    success: Color::Rgb(116, 165, 94),
    error: Color::Rgb(255, 91, 72),
    warning: Color::Rgb(255, 165, 0),
    syn_keyword: Color::Rgb(86, 156, 214),
    syn_string: Color::Rgb(206, 145, 120),
    syn_var: Color::Rgb(156, 220, 254),
    syn_func: Color::Rgb(220, 220, 170),
    syn_comment: Color::Rgb(116, 165, 94),
    syn_number: Color::Rgb(181, 206, 168),
};

pub const LIGHT: TerminalPalette = TerminalPalette {
    bg: Color::Rgb(241, 231, 196),
    surface_1: Color::Rgb(236, 225, 184),
    surface_2: Color::Rgb(230, 220, 178),
    surface_3: Color::Rgb(224, 213, 168),
    border: Color::Rgb(199, 186, 133),
    text: Color::Rgb(58, 53, 39),
    text_strong: Color::Rgb(42, 38, 23),
    text_muted: Color::Rgb(96, 91, 71),
    text_faint: Color::Rgb(101, 96, 75),
    accent: Color::Rgb(31, 102, 89),
    accent_2: Color::Rgb(141, 55, 64),
    accent_rust: Color::Rgb(135, 74, 48),
    mix_target: Color::Rgb(0, 0, 0),
    success: Color::Rgb(8, 99, 38),
    error: Color::Rgb(157, 43, 32),
    warning: Color::Rgb(125, 72, 0),
    syn_keyword: Color::Rgb(39, 74, 134),
    syn_string: Color::Rgb(138, 67, 38),
    syn_var: Color::Rgb(47, 63, 110),
    syn_func: Color::Rgb(106, 83, 31),
    syn_comment: Color::Rgb(82, 95, 54),
    syn_number: Color::Rgb(47, 95, 69),
};
