import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { dark, light } from '../src/lib/tokens/palette.ts';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '../src/lib/tokens/colors.css');

const block = (sel, p) =>
  `${sel} {\n` +
  Object.entries(p)
    .map(([k, v]) => `  --sv-${k}: ${v};`)
    .join('\n') +
  '\n}\n';

const css =
  `/* GENERATED by scripts/build-tokens.mjs — do not edit by hand. */\n` +
  block(':root', dark) +
  `@media (prefers-color-scheme: light) {\n` +
  block('  :root:not([data-theme="dark"])', light) +
  `}\n` +
  block('[data-theme="light"]', light) +
  block('[data-theme="dark"]', dark);

writeFileSync(out, css);
console.log('wrote', out);
